- name: Demo on tags
  hosts: localhost
  tasks:
    - name: Print AWS
      debug:
        msg: AWS
      tags:
        - AWS

    - name: Print AZURE
      debug:
        msg: AZURE
      tags:
        - AZURE