- name: Setup roboshop project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load Frontend Role
      role: frontend

- name: Setup roboshop project -- MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load MongoDb Role
      role: mongodb

- name: Setup roboshop project -- Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load Catalogue Role
      role: catalogue

- name: Setup roboshop project -- Redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load Redis Role
      role: redis

- name: Setup roboshop project -- User Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: Load User Role
      role: user

- name: Setup roboshop project -- Redis Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: Load Cart Role
      role: cart

- name: Setup roboshop project -- MySQL Component
  hosts: MYSQL
  become: yes
  tags:
    - mysql
  roles:
    - name: Load MySQL Role
      role: mysql

- name: Setup roboshop project -- Shipping Component
  hosts: SHIPPING
  become: yes
  tags:
    - shipping
  roles:
    - name: Load Shipping Role
      role: shipping

- name: Setup roboshop project -- RabbitMQ Component
  hosts: RABBITMQ
  become: yes
  tags:
    - rabbitmq
  roles:
    - name: Load RabbitMQ Role
      role: rabbitmq

- name: Setup roboshop project -- Payment Component
  hosts: PAYMENT
  become: yes
  tags:
    - payment
  roles:
    - name: Load Payment Role
      role: payment
