- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Download Package
  include_role:
    name: common
    tasks_from: download.yml
  vars:
    APP_DIR: /usr/share/nginx/html
    EXTRACT_DIR: /usr/share/nginx
    APP_TYPE: web

- name: Copy Nginx RoboShop Config
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: ENV is not defined

- name: Update Nginx RoboShop Config
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  when: ENV is defined

- name: Update Nginx Main Config file
  copy:
    src:  nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nignx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
  ignore_errors: true

- name: Setup Filebeat
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: false
    FILENAME: /var/log/nginx/access.log
    APPTYPE: NGINX

