- name: Remove old content
  ansible.builtin.file:
    path: "{{APP_DIR}}"
    state: absent

- name: Download Packages from GitHUb
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp
  when: APP_VERSION is not defined

- name: Download Package from Nexus
  include_role:
    name: common
    tasks_from: download-from-nexus
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp
  when: APP_VERSION is defined