- name: Setup Azure Cli
  block:
    - name: Install AZ Cli
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Copy Az repo
      copy:
        src: az.repo
        dest: /etc/yum.repos.d/az.repo

    - name: Install Az Extention
      shell: az extension add --name azure-devops


- name: Login to Azure Devops
  shell: echo {{PAT}} | az devops login
