- name: Install NodeJS
  yum:
    name:
      - maven
    state: installed

- name: Add RoboShop User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Project User

-- name: Download Package
   include_role:
     name: common
     tasks_from: download.yml
   vars:
     APP_DIR: "/home/roboshop/{{COMPONENT}}"
     APP_TYPE: java

 - name: Copy SystemD file
  copy:
    src: systemd.service.txt
    dest: /etc/systemd/system/{{COMPONENT}}.service
  when: ENV is not defined

- name: Update SystemD file
  template:
    src: systemd.service.txt
    dest: /etc/systemd/system/{{COMPONENT}}.service
  when: ENV is defined


- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Setup Filebeat
  include_role:
    name: common
    tasks_from: filebeat.yml
  vars:
    IS_STRUCTURED: false
    FILENAME: /var/log/{{COMPONENT}}.log
    APPTYPE: JAVA
